export const CREATE_XML_AND_SEND_MAIL_SUCCESS =
  'CREATE_XML_AND_SEND_MAIL_SUCCESS';
export const CREATE_XML_AND_SEND_MAIL_FAIL = 'CREATE_XML_AND_SEND_MAIL_FAIL';
export const GET_CONTACT_LIST_SUCCESS = 'GET_CONTACT_LIST_SUCCESS';
export const GET_CONTACT_LIST_FAIL = 'GET_CONTACT_LIST_FAIL';
